---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: {{.Values.namespace}}
  labels: {{include "infra-helm-chart.labels" . | indent 4}}
data: {{- template "infra-helm-chart.configData" .}}
