apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-limit-range
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - default:
        memory: {{.Values.resources.limits.memory}}
        cpu: {{.Values.resources.limits.cpu}}
      defaultRequest:
        memory: {{.Values.resources.requests.memory}}
        cpu: {{.Values.resources.requests.cpu}}
      type: Container
