apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infra-helm-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "infra-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "infra-helm-chart.labels" . | nindent 6 }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy: {{ include "infra-helm-chart.deployStrategy" . | indent 4 }}
  template:
    metadata:
      labels: {{ include "infra-helm-chart.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: {{ .Values.image.initContainerImg }}
          args:
            - sleep
            - "80"
      imagePullSecrets:
        - name: {{ .Release.Name }}-robocop
      containers:
        - name: {{ .Chart.Name }}-consumer
          image: {{ .Values.image.containerImg }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BROKER_0
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: broker_0
            - name: BROKER_1
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: broker_1
            - name: BROKER_2
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: broker_2
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: client_id
            - name: TOPIC
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: topic
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: password
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: dbhost
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: dbport
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: db
