apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Values.istio.namespace }}
spec:
  hosts:
  - {{ .Values.istio.hostname.kafka_broker_0 }}
  - {{ .Values.istio.hostname.kafka_broker_1 }}
  - {{ .Values.istio.hostname.kafka_broker_2 }}
  tcp:
  - match:
    - port: {{ .Values.istio.port.kafka_port }}  # to match the gateway port basically to bind this to gateway
    route:
    - destination:
        host: {{ .Values.istio.hostname.kafka_broker_0 }}
        port:
          number: {{ .Values.istio.port.kafka_port }}
  - match:
    - port: {{ .Values.istio.port.kafka_port }}  # to match the gateway port basically to bind this to gateway
    route:
    - destination:
        host: {{ .Values.istio.hostname.kafka_broker_1 }}
        port:
          number: {{ .Values.istio.port.kafka_port }}
  - match:
    - port: {{ .Values.istio.port.kafka_port }}  # to match the gateway port basically to bind this to gateway
    route:
    - destination:
        host: {{ .Values.istio.hostname.kafka_broker_2 }}
        port:
          number: {{ .Values.istio.port.kafka_port }}