---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
  labels: {{include "infra-helm-chart.labels" . | indent 4 }}
type: {{ .Values.secret.type }}
data:
  {{- template "infra-helm-chart.secretData" .}}